### ISSUE TITLE
I can't get the query plugin to return any rows.

### ISSUE THREAD

**Issue by 1Mark** [protegeproject/sparql-query-plugin#15]
It only returns the names of the columns that are in the select statement and regardless of what I do no rows are returned at all.

**Comment by csnyulas** [comment]
Are you sure that you try this in the "SPARQL Query" and not the ["Snap SPARQL Query" view](https://github.com/protegeproject/snap-sparql-query)?

What happens if you execute the sample query provided in the plugin:

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?subject ?object
	WHERE { ?subject rdfs:subClassOf ?object }
```

If you still can't see any results, can you send us the ontology, and the query you are trying to execute, so that we can see what's going on?

**Comment by 1Mark** [comment]
Um I can't perform any queries whatsoever. Even the sample query returns nothing. See image please.

![screenshot from 2017-10-24 08-57-14](https://user-images.githubusercontent.com/15360245/31931023-b03ae7c4-b899-11e7-8c31-daf46a6ceca0.png)

**Comment by 1Mark** [comment]
Same thing is happening for me on windows.

**Comment by csnyulas** [comment]
May I ask what was the reason for closing this ticket? Have you found a solution? Can you share it with us? Did you have an ontology with classes and subclasses loaded when you ran the query?

**Comment by 1Mark** [comment]
Did you have an ontology with classes and subclasses loaded when you ran the query? Initially, I did it didn't work I believe after updating I forgot to re-open it. So yes indeed that was the issue. Apologies.

**Comment by csnyulas** [comment]
We don't delete history :))
(I mean, it is fine to keep it. Once it has been closed, it doesn't bother anyone.)
